# Remove version as it's obsolete in newer Docker Compose

services:
  ai-agent-demo:
    build: .
    container_name: smart-mirror-agent
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      # Add API keys when needed
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      # Mount output directory to host for persistent storage
      - ./ai-agent-demo-factory-backend/crawl4ai-agent/output:/app/backend/crawl4ai-agent/output
      # Mount logs directory to host for persistent log storage
      - ./logs:/app/backend/crawl4ai-agent/output/logs
      # Mount source code for development (optional)
      - ./ai-agent-demo-factory-backend:/app/backend
      - ./crawl4ai:/app/crawl4ai
      # Mount config files
      - ./CLAUDE.md:/app/CLAUDE.md
    ports:
      # Expose port for proxy server (replaces static mirrors)
      - "8000:8000"

    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - ai-agent-network

  # Future: Add database service when learning system is implemented
  # ai-agent-db:
  #   image: postgres:15-alpine
  #   container_name: ai-agent-database
  #   environment:
  #     - POSTGRES_DB=ai_agent_patterns
  #     - POSTGRES_USER=aiagent
  #     - POSTGRES_PASSWORD=secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge

# volumes:
#   postgres_data:
